##############################################################
#
#                   DO NOT EDIT THIS FILE!
#
##############################################################

# If the tool is built out of the kit, PIN_ROOT must be specified in the make invocation and point to the kit root.
PIN_ROOT = pin
# ifdef PIN_ROOT
# CONFIG_ROOT := $(PIN_ROOT)/source/tools/Config
# else
# CONFIG_ROOT := ../Config
# endif
# include $(CONFIG_ROOT)/makefile.config
# include makefile.rules
# include $(TOOLS_ROOT)/Config/makefile.default.rules
MKDIR_P = mkdir -p

INCLUDE_PATH = -Iinclude -I$(PIN_ROOT)/source/include/pin -I$(PIN_ROOT)/source/include/pin/gen -isystem $(PIN_ROOT)/extras/stlport/include -isystem $(PIN_ROOT)/extras/libstdc++/include -isystem $(PIN_ROOT)/extras/crt/include -isystem $(PIN_ROOT)/extras/crt/include/arch-x86 -isystem $(PIN_ROOT)/extras/crt/include/kernel/uapi -isystem $(PIN_ROOT)/extras/crt/include/kernel/uapi/asm-x86 -I$(PIN_ROOT)/extras/components/include -I$(PIN_ROOT)/extras/xed-ia32/include/xed -I$(PIN_ROOT)/source/tools/InstLib
CXXFLAGS = -std=c++11 -g3 -Wall  -Wno-unknown-pragmas -D__PIN__=1 -DPIN_CRT=1 -fno-stack-protector -fno-exceptions -funwind-tables -fasynchronous-unwind-tables -fno-rtti -DTARGET_IA32 -DHOST_IA32 -DTARGET_LINUX -fabi-version=2  -O3 -fomit-frame-pointer -fno-strict-aliasing -m32
ISYSTEM_PATH = -isystem $(PIN_ROOT)/extras/stlport/include -isystem $(PIN_ROOT)/extras/libstdc++/include -isystem $(PIN_ROOT)/extras/crt/include -isystem $(PIN_ROOT)/extras/crt/include/arch-x86 -isystem $(PIN_ROOT)/extras/crt/include/kernel/uapi -isystem $(PIN_ROOT)/extras/crt/include/kernel/uapi/asm-x86
LD_PATH = -L$(PIN_ROOT)/ia32/runtime/pincrt -L$(PIN_ROOT)/ia32/lib -L$(PIN_ROOT)/ia32/lib-ext -L$(PIN_ROOT)/extras/xed-ia32/lib -lpin -lxed $(PIN_ROOT)/ia32/runtime/pincrt/crtendS.o -lpin3dwarf  -ldl-dynamic -nostdlib -lstlport-dynamic -lm-dynamic -lc-dynamic -lunwind-dynamic
LD_FLAGS = -g3 -shared -Wl,--hash-style=sysv $(PIN_ROOT)/ia32/runtime/pincrt/crtbeginS.o -Wl,-Bsymbolic -Wl,--version-script=$(PIN_ROOT)/source/include/pin/pintool.ver -fabi-version=2 -m32
OBJ_DIR = obj-ia32
OBJECTS = ${addprefix src/, ${patsubst %.cpp,%.o, ${filter %.cpp,${shell ls src/}}}}
VPATH = src:include


$(shell ${MKDIR_P} ${OBJ_DIR})

${OBJ_DIR}/detector.so: $(OBJECTS)
	g++ ${LD_FLAGS} -g -o $@ $(OBJECTS) ${LD_PATH}

$(OBJECTS) : %.o: %.cpp
	g++ ${INCLUDE_PATH} ${CXXFLAGS} ${ISYSTEM_PATH} -g -c -o $@ $<

clean:
	rm -rf src/*.o
	rm -rf ${OBJ_DIR}

test:
	pin/pin -t obj-ia32/detector.so -- testsets/test1

##############################################################
#
#                   DO NOT EDIT THIS FILE!
#
##############################################################